pos(be_1,vbz).
pos(the_2,dt).
pos(size_3,nn).
pos(of_4,in).
pos(the_5,dt).
pos(blue_6,jj).
pos(ball_7,nn).
pos(the_8,dt).
pos(same_9,jj).
pos(as_10,in).
pos(the_11,dt).
pos(pink_12,jj).
pos(object_13,nn).
cop(same_9,be_1).
det(size_3,the_2).
nsubj(same_9,size_3).
case(ball_7,of_4).
det(ball_7,the_5).
amod(ball_7,blue_6).
nmod_of(size_3,ball_7).
det(same_9,the_8).
case(object_13,as_10).
det(object_13,the_11).
amod(object_13,pink_12).
nmod_as(same_9,object_13).
is_a(size,parameter).
is_a(size,free_rich_company_datum).
is_a(size,information).
is_a(size,factor).
is_a(size,characteristic).
is_a(object,user_defined_type).
is_a(object,item).
is_a(object,concept).
is_a(object,term).
is_a(object,element).

is_a(size,parameter).
is_a(size,free_rich_company_datum).
is_a(size,information).
is_a(size,factor).
is_a(size,characteristic).
is_a(object,user_defined_type).
is_a(object,item).
is_a(object,concept).
is_a(object,term).
is_a(object,element).
value(blue_6,ball_7).
value(pink_12,object_13).
value(same_9,size_3).
property_type(size_3,ball_7).
is_a(size_3,same_9).
part_whole(size_3,ball_7).
values(ball,7,[blue]).
values(object,13,[pink]).
values(size,3,[same]).
