pos(be,vbz).
pos(the,dt).
pos(size,nn).
pos(of,in).
pos(the,dt).
pos(ball,nn).
pos(the,dt).
pos(same,jj).
pos(as,in).
pos(the,dt).
pos(cyan,jj).
pos(thing,nn).
cop(same,be).
det(size,the).
nsubj(same,size).
case(ball,of).
det(ball,the).
nmod_of(size,ball).
det(same,the).
case(thing,as).
det(thing,the).
amod(thing,cyan).
nmod_as(same,thing).
is_a(size,parameter).
is_a(size,free_rich_company_datum).
is_a(size,information).
is_a(size,factor).
is_a(size,characteristic).
is_a(thing,symptom).
is_a(thing,noun).
is_a(thing,film).
is_a(thing,word).
is_a(thing,addition).

is_a(size,parameter).
is_a(size,free_rich_company_datum).
is_a(size,information).
is_a(size,factor).
is_a(size,characteristic).
is_a(thing,symptom).
is_a(thing,noun).
is_a(thing,film).
is_a(thing,word).
is_a(thing,addition).
value(cyan,thing).
value(same,size).
property_type(size,ball).
is_a(size,same).
part_whole(size,ball).
values(ball,[]).
values(size,[same]).
values(thing,[cyan]).
