pos(how_1,wrb).
pos(many_2,jj).
pos(thing_3,nns).
pos(have_4,vbp).
pos(the_5,dt).
pos(same_6,jj).
pos(color_7,nn).
pos(as_8,in).
pos(the_9,dt).
pos(cube_10,nn).
advmod(many_2,how_1).
amod(thing_3,many_2).
nsubj(have_4,thing_3).
det(color_7,the_5).
amod(color_7,same_6).
dobj(have_4,color_7).
case(cube_10,as_8).
det(cube_10,the_9).
nmod_as(have_4,cube_10).

value(many_2,thing_3).
value(same_6,color_7).
values(color,7,[same]).
values(thing,3,[many]).
values(cube,10,[]).
